# Generated by Django 3.1 on 2021-06-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatform',
            name='base_url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flatform',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
