# Generated by Django 3.1 on 2021-06-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210616_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='base_url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
