# Generated by Django 3.1 on 2021-06-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_base_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='base_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='flatform',
            old_name='base_url',
            new_name='url',
        ),
    ]
