# Generated by Django 3.1 on 2021-06-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210616_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatform',
            name='select_locatoin',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
