# Generated by Django 3.1 on 2021-06-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_flatform_select_locatoin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatform',
            name='select_locatoin',
        ),
    ]
