# Generated by Django 3.1 on 2021-06-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_flatform_select_locatoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatform',
            name='a_tag_class_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatform',
            name='select_location',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
