# Generated by Django 3.1 on 2021-06-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210616_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
